server:
  port: 8080

spring:
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    datasource:
        url: jdbc:mysql://localhost:3306/yzh?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    type-aliases-package: com.yzh
#    config-location: classpath:/mybatis-setting.xml
    mapperLocations: classpath:/mapper/**/*.xml
